name: build-parcel
run-name: building ${{ github.actor }} commit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x,18.x]
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build
      - name: Zip build for deployment
        run: zip release.zip ./dist/* -r
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build.zip

  